name: Build & Push Backend
inputs:
  github-token:
    required: true
    description: token...
  tag:
    default: latest
    description: tag of image

# https://docs.gradle.org/current/userguide/build_environment.html#setting_a_project_property
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-java

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    #登录到 ghcr
    - name: Log in to registry
      shell: bash
      run: |
        echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build with Gradle
      shell: bash
      # 移除了 -PdockerVersion=${{ inputs.tag }}  因为没有必要
      run: |
        ./gradlew build :apps:console-backend:buildImage
        docker image load -i ./apps/console-backend/build/jib-image.tar
        docker tag santorini-console-backend:latest ghcr.io/${{ github.actor }}/santorini-console-backend:${{ inputs.tag }}
        docker tag santorini-console-backend:latest ghcr.io/${{ github.actor }}/santorini-console-backend:${{ github.sha }}
        docker push -a ghcr.io/${{ github.actor }}/santorini-console-backend
        echo "### 成功发布 :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- ghcr.io/${{ github.actor }}/santorini-console-backend:${{ inputs.tag }}" >> $GITHUB_STEP_SUMMARY
        echo "- ghcr.io/${{ github.actor }}/santorini-console-backend:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
