### token 问题应该查看 kube-apiserver@kube-system 的日志
### 查看
GET {{url}}/apis/apps/v1/namespaces/{{namespace}}/deployments?
    labelSelector=app.kubernetes.io/name=release-name-common-required-santorini-console-backend1
Authorization: Bearer {{JWT}}

### a
GET {{url}}/api/v1/namespaces/{{namespace}}/pods
Authorization: Bearer {{JWT}}

### a
GET {{url}}/api/v1
Authorization: Bearer {{JWT}}

### kubectl auth can-i get pods --token="" --server="https://<ip>:443" -n default
## kubectl auth whoami --token "" --kubeconfig=/root/.kube/config_without_token
### whoami; 带 Bearer 401
POST {{url}}/apis/authentication.k8s.io/v1/selfsubjectreviews
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "apiVersion": "authentication.k8s.io/v1",
  "kind": "SelfSubjectReview"
}

### 本地访问 Token
### a
GET {{url}}/api/v1/namespaces
Authorization: Bearer {{JWT}}